<?php
require_once __DIR__."/../includes/autenticacao.php";exigirAdministrador();require_once __DIR__."/../includes/ligaBD.php";
$erro="";if($_SERVER["REQUEST_METHOD"]==="POST"){$id=filter_var($_POST["id_mensagem"]??null,FILTER_VALIDATE_INT)?:0;if(!tokenCsrfValido($_POST["csrf_token"]??null))$erro="O formulário expirou.";elseif($id>0){$stmt=mysqli_prepare($ligacao,"UPDATE mensagem_contacto SET estado='Lida' WHERE id_mensagem=?");mysqli_stmt_bind_param($stmt,"i",$id);mysqli_stmt_execute($stmt);mysqli_stmt_close($stmt);redirecionar("admin/mensagens.php?estado=lida");}}
$mensagens=[];$r=mysqli_query($ligacao,"SELECT id_mensagem,nome,email,assunto,mensagem,estado,data_envio FROM mensagem_contacto ORDER BY data_envio DESC");while($m=mysqli_fetch_assoc($r))$mensagens[]=$m;
$tituloPagina="Mensagens | Administração";include __DIR__."/../includes/menu.php";
?>
<main class="page"><div class="container"><div class="page-heading heading-actions"><div><span class="eyebrow">Administração</span><h1>Mensagens</h1></div><a class="btn" href="<?php echo $baseUrl;?>/admin/dashboard.php">Dashboard</a></div><?php if(($_GET["estado"]??"")==="lida"):?><div class="sucesso">Mensagem marcada como lida.</div><?php endif;?><?php if($erro):?><div class="erro"><?php echo escapar($erro);?></div><?php endif;?>
<div class="messages-list"><?php if(!$mensagens):?><div class="empty-state"><h2>Sem mensagens</h2></div><?php endif;?><?php foreach($mensagens as $m):?><article class="message-card"><header><div><span class="badge <?php echo $m["estado"]==="Nova"?"badge-warning":"badge-muted";?>"><?php echo escapar($m["estado"]);?></span><h2><?php echo escapar($m["assunto"]);?></h2></div><time><?php echo date("d/m/Y H:i",strtotime($m["data_envio"]));?></time></header><p><strong>De:</strong> <?php echo escapar($m["nome"]);?> — <a href="mailto:<?php echo escapar($m["email"]);?>"><?php echo escapar($m["email"]);?></a></p><div class="message-body"><?php echo nl2br(escapar($m["mensagem"]));?></div><?php if($m["estado"]==="Nova"):?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?php echo escapar(tokenCsrf());?>"><input type="hidden" name="id_mensagem" value="<?php echo (int)$m["id_mensagem"];?>"><button class="btn-small" type="submit">Marcar como lida</button></form><?php endif;?></article><?php endforeach;?></div>
</div></main><?php include __DIR__."/../includes/footer.php";?>
